intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{miniaudio}: libul{miniaudio}: {h c}{**} $impl_libs $intf_libs

libs{miniaudio}: def{miniaudio}: include = ($c.target.system == 'win32-msvc')
def{miniaudio}: libul{miniaudio}

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{miniaudio}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{miniaudio}: bin.lib.version = "-$version.project_id"
else
  lib{miniaudio}: bin.lib.version = "-$version.major.$version.minor"

# Install into the miniaudio/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/miniaudio/
  install.subdirs = true
}
